### ISSUE TITLE
Items all selected by default

### ISSUE THREAD

**Issue by nickyd3141** [ganesh-91/multi-select-react#8]
The multi-select box is working great, but it seems that when a page is reloaded, all of the options are selected by default. Is there a way to make it so by default none are selected?

**Comment by R9Shah** [comment]
The format for adding the options is ,
multiSelect: [
        {value: false, label: "aaa", id: 1},
        {value: false, label: "bbb", id: 2}
      ]

Value: true/false - is the selection criteria.

**Comment by RiyaRently** [comment]
It would be helpful if you can mention the type in the readme file.

**Comment by AvinashRamDulipala** [comment]
How can I get the default selected values list from the options?

**Comment by Shekharb694** [comment]
> 
> 
> How can I get the default selected values list from the options?

Change the "value" attribute to "true" for the options you want to show selected by default.
multiSelect: [
{value: true, label: "aaa", id: 1},
{value: false, label: "bbb", id: 2}
]
